// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggfyvyncgzpnrkiimslu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnZnl2eW5jZ3pwbnJraWltc2x1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjg1NTYsImV4cCI6MjA2NDgwNDU1Nn0.l9PU6lr6C6QW_nsli6SXTDqD0iVcw9bI_-3XLR2dah4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);